### ISSUE TITLE
Several tests in ESAPIValidatorTest appear to fail with certain non-US locales.

### ISSUE THREAD

**Issue by volkertb** [vdbaan/owasp-java-validator#2]
This test fails as follows on a Windows environment I tried it on:

```
at org.owasp.validator.NumberValidator.validate(NumberValidator.java:161)
at org.owasp.validator.NumberValidator.validate(NumberValidator.java:84)
at org.owasp.validator.NumberValidator.validate(NumberValidator.java:110)
at org.owasp.validator.ESAPIValidatorTest.testIsValidDouble(ESAPIValidatorTest.java:209)
    (...)
```

The reason being that the current system locale on the tested environment (nl_NL) treats the dot as a "thousands" separator as opposed to a decimal seprator (which is a comma in the NL locale). As a result, the Number 4.3214 is converted to the long value 43214 (as opposed to 4), which is in fact higher than the specified max value 10.

Of course, the unit test could be configured to run explicitly using a US locale, but if the ESAPI reference implementation does not require this for the test to pass with any locale, it may handle this more smartly somehow.

**Comment by volkertb** [comment]
ESAPIValidatorTest.testIsValidNumber() and ESAPIValidatorTest.testIsValidInteger() appear to fail for the exact same reason.

**Comment by volkertb** [comment]
There is a high probability that the failure cause of ESAPIValidatorTest.testIsValidDate() is also Locale-related.

**Comment by vdbaan** [comment]
Pre-set the locale for the test case, shouldn't fail any more. I will add some Locale tests as a separate issue.
